pipeline {
    agent any
    stages {
        stage ('HelloWorld mit groovy') {
            steps {
                script{
                    HelloWorldlaunchfile.greeting 'geschafft'
                }
            }
        }
    }
}