pipeline {
    agent any 
    stages {
        stage('testing the groove') {
            steps {
                script {
                    rainerLaunch.greeting ' yeah !'
                }
            }
        }
    }
}
