pipeline {
    agent any 
    stages {
        stage('testing my groove') {
            steps {
                script {
                    testthis.greeting 'World'
                }
            }
        }
    }
}
