pipeline {
    agent  any 
    stages {
        stage('testing my groove') {
            steps {
                script {
                    TestThis.greeting 'World'
                }
            }
        }
    }
}
