pipeline {
    agent any 
    stages {
        stage('testing the groove') {
            steps {
                script {
                    groovylaunchfile.greeting ' World !'
                }
            }
        }
    }
}
